// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"time"
)

type User struct {
	ID             string    `json:"id"`
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	Email          string    `json:"email"`
	CreatedAt      time.Time `json:"created_at"`
}

type Video struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Images      string    `json:"images"`
	OriginLink  string    `json:"origin_link"`
	PlayLink    string    `json:"play_link"`
	Status      int32     `json:"status"`
	IsDeleted   bool      `json:"is_deleted"`
	UserID      string    `json:"user_id"`
	CreateAt    time.Time `json:"create_at"`
	CreateBy    string    `json:"create_by"`
	UpdateAt    time.Time `json:"update_at"`
	UpdateBy    string    `json:"update_by"`
}
